# Generated by Django 2.2.6 on 2019-10-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191005_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseballgame',
            old_name='session',
            new_name='username',
        ),
        migrations.AlterUniqueTogether(
            name='baseballgame',
            unique_together={('username', 'real_number', 'created_at')},
        ),
    ]
