# Generated by Django 2.2.6 on 2019-10-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191005_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseballgame',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='try_count',
            field=models.IntegerField(default=0),
        ),
    ]
